/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uflybookingsystem;

import BusinessObjects.*;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import javax.swing.*;
import java.util.*;

/**
 *
 * @author Callan
 */
public final class BookingForm extends javax.swing.JFrame {
    private static ArrayList<Location> locationsList;
    private static ArrayList<Flight> flightsList;
    private final Booking booking;
    private Flight flight;
    private Location location;
    private String departure = "";
    private String destination = "";
    private final SimpleDateFormat formatter;
    private BookingFinalForm bookingFinalForm;
    
    /**
     * Creates new form BookForm
     */
    public BookingForm() {
        setContentPane(new JLabel(new ImageIcon(getClass().getResource("/background_bookingForm.jpg"))));
        locationsList = new ArrayList<>();
        flightsList = new ArrayList<>();
        location = new Location();
        booking = new Booking();
        flight = new Flight();
        formatter = new SimpleDateFormat("dd/MM/yyyy HH:mm");
        initComponents();
        pnlChooseClass.setOpaque(false);
        lblChooseTheClass.setVisible(false);
        cboChooseTheClass.setVisible(false);
        btnBook.setVisible(false);
        createCabinClassModel();
        createFromLocationsModel();
        createToLocationsModel();
        createDatesModel();
    }
    
    // Populates the cboChooseTheClass combobox.
    public void createCabinClassModel() {
        for (CabinClass cantype: CabinClass.values() ) {
            cboChooseTheClass.addItem(cantype);
        }
    }
    
    // Populates the cboFrom combobox.
    public void createFromLocationsModel() {
        locationsList = (DatabaseOperations.GetAllLocations());
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (Location loc : locationsList) {
            model.addElement(loc);
        }    
        cboFrom.setModel(model);
    }

    // Populates the cboTo combobox.
    public void createToLocationsModel() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (Location loc : locationsList) {
            if (loc != cboFrom.getSelectedItem()) {
                model.addElement(loc);
            }
        }    
        cboTo.setModel(model);
    }
    
    
    public void createDatesModel() {
        cboDate.removeAllItems();
        location = (Location) cboFrom.getSelectedItem();
        departure = location.getAirportCode();
        location = (Location) cboTo.getSelectedItem();
        destination = location.getAirportCode();
        flightsList = DatabaseOperations.GetAllFlights(departure, destination);
        if (flightsList.isEmpty()) {
            cboDate.addItem("Sorry, there are no available flights.");
        } 
        else {
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            for (Flight flt : flightsList) {
                model.addElement(flt);
            }
            cboDate.setModel(model);
        }
    }
    
    // Run when search for flight is initiated. Only function is to check whether
    // the flight being search for is full or not. If full, then there is no need
    // to display booking information and user is alerted. 
    public boolean isFlightFullCheck(Flight flight) {
        boolean isFlightFull = false;
        Plane planeType = Plane.valueOf(flight.getPlane());
        if (flight.getSeatsTaken() == planeType.getPassengerCapacity()) {
            isFlightFull = true;
        }
        return isFlightFull;
    }
        
    public static void addToLocationsList(Location location) {
        locationsList.add(location);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboFrom = new javax.swing.JComboBox();
        cboTo = new javax.swing.JComboBox();
        lblFrom = new javax.swing.JLabel();
        lblTo = new javax.swing.JLabel();
        lblDateYouWantTTravel = new javax.swing.JLabel();
        cboDate = new javax.swing.JComboBox();
        btnSearch = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        pnlChooseClass = new javax.swing.JPanel();
        lblChooseTheClass = new javax.swing.JLabel();
        cboChooseTheClass = new javax.swing.JComboBox();
        btnBook = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        cboFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboFromActionPerformed(evt);
            }
        });

        cboTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboToActionPerformed(evt);
            }
        });

        lblFrom.setText("From:");

        lblTo.setText("To:");

        lblDateYouWantTTravel.setText("Date you want to travel:");

        cboDate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDateActionPerformed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(255, 102, 0));
        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setMnemonic('c');
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnClose.setBackground(new java.awt.Color(102, 102, 102));
        btnClose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setMnemonic('c');
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        pnlChooseClass.setPreferredSize(new java.awt.Dimension(680, 122));

        lblChooseTheClass.setText("Choose the class:");

        cboChooseTheClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboChooseTheClassActionPerformed(evt);
            }
        });

        btnBook.setBackground(new java.awt.Color(255, 102, 0));
        btnBook.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBook.setForeground(new java.awt.Color(255, 255, 255));
        btnBook.setMnemonic('b');
        btnBook.setText("Book");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlChooseClassLayout = new javax.swing.GroupLayout(pnlChooseClass);
        pnlChooseClass.setLayout(pnlChooseClassLayout);
        pnlChooseClassLayout.setHorizontalGroup(
            pnlChooseClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChooseClassLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlChooseClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlChooseClassLayout.createSequentialGroup()
                        .addComponent(lblChooseTheClass)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlChooseClassLayout.createSequentialGroup()
                        .addComponent(cboChooseTheClass, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        pnlChooseClassLayout.setVerticalGroup(
            pnlChooseClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChooseClassLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lblChooseTheClass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlChooseClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboChooseTheClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDateYouWantTTravel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cboDate, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cboFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblFrom))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblTo)
                                .addComponent(cboTo, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(37, Short.MAX_VALUE))
            .addComponent(pnlChooseClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFrom)
                    .addComponent(lblTo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(lblDateYouWantTTravel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(cboDate))
                .addGap(32, 32, 32)
                .addComponent(pnlChooseClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClose)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        flight = (Flight) cboDate.getSelectedItem();
        flightsList = DatabaseOperations.GetAllFlightsForLocation(departure, destination, cboDate.getSelectedItem().toString());
        if(!cboDate.getSelectedItem().equals("Sorry, there are no available flights." ) && isFlightFullCheck(flight) == false) {
            lblChooseTheClass.setVisible(true);
            cboChooseTheClass.setVisible(true);
            btnBook.setVisible(true);
        }
        else {
            JOptionPane.showMessageDialog(this, "Unfortunately, this flight is fully booked.\n"
                    + "Please check our the flight schedule for other available flights on this route.", 
            "No Available Seats", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void cboChooseTheClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboChooseTheClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboChooseTheClassActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
        bookingFinalForm.dispose();
        MainForm form = new MainForm();
        form.setVisible(true);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void cboFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboFromActionPerformed
        createToLocationsModel();
        createDatesModel();
        if (cboDate.getSelectedItem().toString().equals("Sorry, there are no available flights.")) {
            lblChooseTheClass.setVisible(false);
            cboChooseTheClass.setVisible(false);
            btnBook.setVisible(false);
        }
    }//GEN-LAST:event_cboFromActionPerformed

    private void cboToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboToActionPerformed
        createDatesModel();
        if (cboDate.getSelectedItem().toString().equals("Sorry, there are no available flights.")) {
            lblChooseTheClass.setVisible(false);
            cboChooseTheClass.setVisible(false);
            btnBook.setVisible(false);
        }
    }//GEN-LAST:event_cboToActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        isFlightFullCheck(flight);
        BigDecimal bigDecimalPriceValue = flight.getPrice();
        Double doubleTest = bigDecimalPriceValue.doubleValue();
        CabinClass cabinClass = (CabinClass) cboChooseTheClass.getSelectedItem();
        switch (cabinClass) {
            case ECONOMY_CLASS:
                booking.setPrice(bigDecimalPriceValue);
                booking.setCabinClass(CabinClass.ECONOMY_CLASS.toString());
                break;
            case PRESTIGE_CLASS :
                doubleTest += doubleTest * 0.2;
                booking.setPrice(BigDecimal.valueOf(doubleTest));
                booking.setCabinClass(CabinClass.PRESTIGE_CLASS.toString());
                break;
            case FIRST_CLASS :
                doubleTest += doubleTest * 0.35;
                booking.setPrice(BigDecimal.valueOf(doubleTest));
                booking.setCabinClass(CabinClass.FIRST_CLASS.toString());
                break;
        }
        booking.setFlightNumber(flight.getFlightNumber());
        
        bookingFinalForm = new BookingFinalForm(booking, flight);
        bookingFinalForm.setLocation(800, 0);
        lblChooseTheClass.setVisible(false);
        cboChooseTheClass.setVisible(false);
        btnBook.setVisible(false);
        bookingFinalForm.setVisible(true);
    }//GEN-LAST:event_btnBookActionPerformed

    private void cboDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox cboChooseTheClass;
    private javax.swing.JComboBox cboDate;
    private javax.swing.JComboBox cboFrom;
    private javax.swing.JComboBox cboTo;
    private javax.swing.JLabel lblChooseTheClass;
    private javax.swing.JLabel lblDateYouWantTTravel;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblTo;
    private javax.swing.JPanel pnlChooseClass;
    // End of variables declaration//GEN-END:variables
}
