/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uflybookingsystem;
import BusinessObjects.*;
import java.sql.SQLException;
import javax.swing.*;
import java.text.DecimalFormat;

/**
 *
 * @author Callan
 */
public final class BookingFinalForm extends javax.swing.JFrame { 
    private static Booking booking;
    private static Flight flight;
    private int capacity = 0;
    private boolean isInsuranceValue;
    private final DecimalFormat formatter;
    
    /**
     * Creates new form BookFinalForm
     * @param booking
     * @param flight
     */
    public BookingFinalForm(Booking booking, Flight flight) {
        setContentPane(new JLabel(new ImageIcon(getClass().getResource("/background_bookingFinalForm.jpg"))));
        initComponents();
        formatter = new DecimalFormat("#.00");
        lblFlightNumber.setText(booking.getFlightNumber());
        BookingFinalForm.flight = flight;
        createQuantityModel();
        BookingFinalForm.booking = booking;
    }
    
    // Determines the number of available tickets and populates said value in cboNumOfTickets combobox.
    public void createQuantityModel() {
        cboNumOfTickets.removeAllItems();
        String planeType = flight.getPlane();
        for (Plane plane : Plane.values()) {
            if (plane.toString().equals(planeType)) {
                capacity = plane.getPassengerCapacity();
            }
        }
        int seatsLeft = capacity - flight.getSeatsTaken();
        if(seatsLeft <= 12) {
            for (int i = 1; i <= seatsLeft; i++){
                cboNumOfTickets.addItem(i);
            }
        }
        else {
            for (int i = 1; i <= 12; i ++){
                cboNumOfTickets.addItem(i);
            }
        }
    }

    // Calculates final price for booking.
    private void bookFlight() {
        booking.setQuantity( (Integer) cboNumOfTickets.getSelectedItem());
        Double finalPrice = booking.getPrice().doubleValue();
        try {
            int newSeatsTaken = flight.getSeatsTaken() + booking.getQuantity();
            if (newSeatsTaken <= capacity) {
                flight.setSeatsTaken(newSeatsTaken);
                DatabaseOperations.UpdateFlight(flight);
                createQuantityModel();
                if (isInsuranceValue == true) {
                    finalPrice = (finalPrice * booking.getQuantity()) + 20;
                }
                else {
                    finalPrice = finalPrice * booking.getQuantity();
                }
                DatabaseOperations.AddBooking(booking);
            JOptionPane.showMessageDialog(this, "Transaction successful. The amount of $" + formatter.format(finalPrice) + " has been debited from your account.", 
                        "Successful Booking", JOptionPane.INFORMATION_MESSAGE);
            }
            
        } 
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error in communicating with database", 
                   "Communication Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFlight = new javax.swing.JLabel();
        cboNumOfTickets = new javax.swing.JComboBox();
        lblFlightNumber = new javax.swing.JLabel();
        lblInsurance = new javax.swing.JLabel();
        isInsurance = new javax.swing.JCheckBox();
        btnBookFlight = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        lblHowManyTicketsWould = new javax.swing.JLabel();
        lblYouLikeToGet = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblFlight.setText("Flight:");

        cboNumOfTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNumOfTicketsActionPerformed(evt);
            }
        });

        lblFlightNumber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFlightNumber.setText("\"flight number here\"");

        lblInsurance.setText("Would you like to get insurance?");

        isInsurance.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                isInsuranceItemStateChanged(evt);
            }
        });

        btnBookFlight.setBackground(new java.awt.Color(255, 102, 0));
        btnBookFlight.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBookFlight.setForeground(new java.awt.Color(255, 255, 255));
        btnBookFlight.setMnemonic('c');
        btnBookFlight.setText("Book The Flight");
        btnBookFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookFlightActionPerformed(evt);
            }
        });

        btnClose.setBackground(new java.awt.Color(102, 102, 102));
        btnClose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setMnemonic('c');
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        lblHowManyTicketsWould.setText("How many tickets would");

        lblYouLikeToGet.setText("you like to get?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBookFlight)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblInsurance)
                        .addGap(114, 114, 114)
                        .addComponent(isInsurance))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(137, 137, 137))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblFlightNumber)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cboNumOfTickets, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblHowManyTicketsWould)
                                .addComponent(lblYouLikeToGet)))))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFlight)
                    .addComponent(lblHowManyTicketsWould))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblYouLikeToGet)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFlightNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboNumOfTickets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addComponent(lblInsurance))
                    .addComponent(isInsurance))
                .addGap(45, 45, 45)
                .addComponent(btnBookFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 20, Short.MAX_VALUE)
                .addGap(46, 46, 46)
                .addComponent(btnClose)
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBookFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookFlightActionPerformed
        bookFlight();
        this.dispose();
    }//GEN-LAST:event_btnBookFlightActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void isInsuranceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_isInsuranceItemStateChanged
        isInsuranceValue = !isInsuranceValue;
        booking.setInsurance(isInsuranceValue);
    }//GEN-LAST:event_isInsuranceItemStateChanged

    private void cboNumOfTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNumOfTicketsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboNumOfTicketsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingFinalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingFinalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingFinalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingFinalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new BookingFinalForm(booking, flight).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookFlight;
    private javax.swing.JButton btnClose;
    private javax.swing.JComboBox cboNumOfTickets;
    private javax.swing.JCheckBox isInsurance;
    private javax.swing.JLabel lblFlight;
    private javax.swing.JLabel lblFlightNumber;
    private javax.swing.JLabel lblHowManyTicketsWould;
    private javax.swing.JLabel lblInsurance;
    private javax.swing.JLabel lblYouLikeToGet;
    // End of variables declaration//GEN-END:variables
}
