/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uflybookingsystem;

import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Callan
 */
public class ImportFeedBackForm extends javax.swing.JFrame { 
    private static ImportResult importResult;
    private BufferedReader bufferedReader;
    private String outputContent = "";
    private String[] fileContent;
    private static File file;

    /**
     * Creates new form ImportFeedBackForm
     * @param importRslt
     * @param fle
     * @throws java.io.FileNotFoundException
     */
    public ImportFeedBackForm(ImportResult importRslt, File fle) throws IOException {
        importResult = importRslt;
        setContentPane(new JLabel(new ImageIcon(getClass().getResource("/background_importFeedBackForm.jpg"))));
        initComponents();
        file = fle;
        bufferedReader = new BufferedReader(new FileReader(file));
        String line = bufferedReader.readLine();
        for(line = bufferedReader.readLine(); line != null; line = bufferedReader.readLine()) {
            fileContent = line.split(",");
            for (String item : fileContent) {
                outputContent += "   " + item + "\t";
            }
            outputContent += "\n";
        }
        txtOutput.setText(outputContent);
        lblTotalRowsValue.setText(String.valueOf(this.importResult.getTotalRows()));
        lblImportedRowsValue.setText(String.valueOf(this.importResult.getImportedRows()));
        lblIFailedRowsValue.setText(String.valueOf(this.importResult.getFailedRows()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClose = new javax.swing.JButton();
        lblTotalRows = new javax.swing.JLabel();
        lblImportedRows = new javax.swing.JLabel();
        lblFailedRows = new javax.swing.JLabel();
        lblTotalRowsValue = new javax.swing.JLabel();
        lblImportedRowsValue = new javax.swing.JLabel();
        lblIFailedRowsValue = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnClose.setBackground(new java.awt.Color(102, 102, 102));
        btnClose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setMnemonic('c');
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        lblTotalRows.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotalRows.setText("Total Rows:");

        lblImportedRows.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblImportedRows.setText("Imported Rows:");

        lblFailedRows.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFailedRows.setText("Failed Rows:");

        lblTotalRowsValue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotalRowsValue.setText("\"\"");

        lblImportedRowsValue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblImportedRowsValue.setText("\"\"");

        lblIFailedRowsValue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIFailedRowsValue.setText("\"\"");

        txtOutput.setEditable(false);
        txtOutput.setColumns(20);
        txtOutput.setRows(5);
        jScrollPane1.setViewportView(txtOutput);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFailedRows, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImportedRows, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotalRows, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblIFailedRowsValue, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImportedRowsValue, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotalRowsValue, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(264, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalRows)
                    .addComponent(lblTotalRowsValue))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImportedRows)
                    .addComponent(lblImportedRowsValue))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFailedRows)
                    .addComponent(lblIFailedRowsValue))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
        MainForm form = new MainForm();
        form.setVisible(true);
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImportFeedBackForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImportFeedBackForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImportFeedBackForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImportFeedBackForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ImportFeedBackForm(importResult, file).setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(ImportFeedBackForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFailedRows;
    private javax.swing.JLabel lblIFailedRowsValue;
    private javax.swing.JLabel lblImportedRows;
    private javax.swing.JLabel lblImportedRowsValue;
    private javax.swing.JLabel lblTotalRows;
    private javax.swing.JLabel lblTotalRowsValue;
    private javax.swing.JTextArea txtOutput;
    // End of variables declaration//GEN-END:variables
}
