/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uflybookingsystem;

import javax.swing.*;

/**
 *
 * @author Callan
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form mainForm
     */
    public MainForm() {
        setContentPane(new JLabel(new ImageIcon(getClass().getResource("/background_mainForm.jpg"))));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnImportLocationsAndFlights = new javax.swing.JButton();
        btnBookAFlight = new javax.swing.JButton();
        btnClose1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnImportLocationsAndFlights.setBackground(new java.awt.Color(255, 102, 0));
        btnImportLocationsAndFlights.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnImportLocationsAndFlights.setForeground(new java.awt.Color(255, 255, 255));
        btnImportLocationsAndFlights.setMnemonic('a');
        btnImportLocationsAndFlights.setText("Import Locations and Flights");
        btnImportLocationsAndFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportLocationsAndFlightsActionPerformed(evt);
            }
        });

        btnBookAFlight.setBackground(new java.awt.Color(255, 102, 0));
        btnBookAFlight.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBookAFlight.setForeground(new java.awt.Color(255, 255, 255));
        btnBookAFlight.setMnemonic('p');
        btnBookAFlight.setText("Book a Flight");
        btnBookAFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookAFlightActionPerformed(evt);
            }
        });

        btnClose1.setBackground(new java.awt.Color(102, 102, 102));
        btnClose1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClose1.setForeground(new java.awt.Color(255, 255, 255));
        btnClose1.setMnemonic('c');
        btnClose1.setText("Close");
        btnClose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClose1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(197, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBookAFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnImportLocationsAndFlights, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(144, 144, 144))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnClose1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(btnImportLocationsAndFlights)
                .addGap(65, 65, 65)
                .addComponent(btnBookAFlight)
                .addGap(68, 68, 68)
                .addComponent(btnClose1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImportLocationsAndFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportLocationsAndFlightsActionPerformed
        this.dispose();
        ImportLocationsAndFlightsForm form = new ImportLocationsAndFlightsForm();
        form.setVisible(true);
        
    }//GEN-LAST:event_btnImportLocationsAndFlightsActionPerformed

    private void btnBookAFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookAFlightActionPerformed
        if (DatabaseOperations.GetAllLocations().isEmpty() && DatabaseOperations.GetAllFlights().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please export .txt files containing location and flight details.", "No locations or flights exported to database", JOptionPane.INFORMATION_MESSAGE);
        }
        else if (DatabaseOperations.GetAllLocations().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please export a .txt file containing location details.", "No locations exported to database", JOptionPane.INFORMATION_MESSAGE);
        }
        else if (DatabaseOperations.GetAllFlights().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please export a .txt file containing flight details.", "No flights exported to database", JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            this.dispose();
            BookingForm form = new BookingForm();
            form.setVisible(true);    
        }

    }//GEN-LAST:event_btnBookAFlightActionPerformed

    private void btnClose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClose1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnClose1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookAFlight;
    private javax.swing.JButton btnClose1;
    private javax.swing.JButton btnImportLocationsAndFlights;
    // End of variables declaration//GEN-END:variables
}
